name: Issue Greeting

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            Thanks for opening your first issue! We'll take a look as soon as possible.

            In the meantime, please make sure you've provided:
            - Chrome version
            - Extension version (from manifest.json)
            - Steps to reproduce the issue
            - Expected vs actual behavior
